<h1>Task 1: Create a 4X2 integer array and Prints its attributes</h1>

In [1]:
import numpy as np

firstArray = np.empty([4,2], dtype = np.uint16) 
print("Printing Array")
print(firstArray)

print("Printing numpy array Attributes")
print("1> Array Shape is: ", firstArray.shape)
print("2>. Array dimensions are ", firstArray.ndim)
print("3>. Length of each element of array in bytes is ", firstArray.itemsize)

Printing Array
[[119   0]
 [ 97   0]
 [114   0]
 [110   0]]
Printing numpy array Attributes
1> Array Shape is:  (4, 2)
2>. Array dimensions are  2
3>. Length of each element of array in bytes is  2


<h1>Task 2: <h2>Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10<> </h1>

In [2]:
print("Creating 5X2 array using numpy.arange")
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

Creating 5X2 array using numpy.arange
[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


<h1>Task 3: <h2>Following is the provided numPy array. return array of items in the third column from all rows
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])</h2></h1>

In [8]:
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[33 66 99]


<h1>Task 4: <h2>Return array of odd rows and even columns from below numpy array sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])</h2></h1>

In [16]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
print("Printing Input Array")
print(sampleArray)

print("\n Printing odd rows and evem columns ")
newArray = sampleArray[1::2, ::2]
print(newArray)

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing odd rows and evem columns 
[[15 21]
 [39 45]]


<h1>Task 5: <h2>Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])</h2>
</h1>

In [24]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])
result = arrayOne + arrayTwo

print('Orignal Array \n',result)
for i in range(2):
    for j in range(3):
        temp = result[i,j] * result[i,j]
        result[i,j] = temp
        

print('Array after taking squares \n',result)
        

Orignal Array 
 [[20 39 33]
 [25 25 28]]
Array after taking squares 
 [[ 400 1521 1089]
 [ 625  625  784]]


<h1>Task 6: <h2>Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.</h2>
</h1>

In [32]:
print("Creating 8X3 array using numpy.arange")
sampleArray = np.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print(sampleArray)

subarray_one = sampleArray[:2,:3]
print('Subarray one \n',subarray_one)

subarray_two = sampleArray[2:4,:3]
print('Subarray two \n',subarray_two)

subarray_three = sampleArray[4:6,:3]
print('Subarray three \n',subarray_three)

subarray_four = sampleArray[6:8,:3]
print('Subarray four \n',subarray_four)

Creating 8X3 array using numpy.arange
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]
Subarray one 
 [[10 11 12]
 [13 14 15]]
Subarray two 
 [[16 17 18]
 [19 20 21]]
Subarray three 
 [[22 23 24]
 [25 26 27]]
Subarray four 
 [[28 29 30]
 [31 32 33]]


<h1>Task 7: <h2>Sort following NumPy array first by the second row, then by the second columns sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])</h2> </h1>

In [33]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


<h1>Task 8: <h2>Print max from axis 0 and min from axis 1 from the following 2-D array. sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])</h2></h1>

In [41]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

arr_axis_zero = np.array([0,1,2])
arr_axis_one = np.array([0,1,2])

print(sampleArray)
arr_axis_zero[0] = max(sampleArray[0:3,0])
arr_axis_one[0] = min(sampleArray[0,0:3])

for i in range(3):
    if arr_axis_zero[i] < max(sampleArray[0:3,i]):
        arr_axis_zero[i] = max(sampleArray[0:3,i])
        
for i in range(3):
    if arr_axis_one[i] < min(sampleArray[i,0:3]):
        arr_axis_one[i] = min(sampleArray[i,0:3])

        
print('Max of axis zero \n',arr_axis_zero)
print('Min of axis one \n',arr_axis_one)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Max of axis zero 
 [82 94 73]
Min of axis one 
 [34 12 53]


<h1>Task 9:<h2>Delete the second column from a given array and insert the following new column in its place.
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = numpy.array([[10,10,10]])</h2></h1>

In [56]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([10,10,10])
print(sampleArray)
sampleArray = np.delete(sampleArray, 1, axis = 1)
sampleArray = np.insert(sampleArray, 1,newColumn, axis=1)


print(sampleArray)



[[34 43 73]
 [82 22 12]
 [53 94 66]]
[[34 10 73]
 [82 10 12]
 [53 10 66]]
